# File: .github/workflows/OIDC_workflow.yml
name: Sync Storage Account

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: rnakamine/azure-files-upload@v1.0.0
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        source: ./templates
        destination: https://templatez.file.core.windows.net/teste
        extra_args: '--account-name templatez'

  