# File: .github/workflows/OIDC_workflow.yml
name: AzureLoginSample
on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
        az storage file upload-batch  --account-name templatez  --destination https://templatez.file.core.windows.net/teste --source templates --destination-path subpasta