# File: .github/workflows/OIDC_workflow.yml
name: AzureLoginSample
on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: rnakamine/azure-files-upload@v1.0.0
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        source: .
        destination: teste