# File: .github/workflows/OIDC_workflow.yml
name: AzureLoginSample
on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Acessar diretório raiz do projeto
      run: |
        cd ${{ github.workspace }}
        ls

    - uses: rnakamine/azure-files-upload@v1.0.0
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        source: .
        destination: templatez

    
    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Azure Blob Upload with Destination folder defined
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container_name: templatez
        source_folder: templates
        destination_folder: teste
        clean_destination_folder: true