# File: .github/workflows/OIDC_workflow.yml
name: AzureLoginSample
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/checkout@v2
    - uses: cahaseler/azure-fileshare-upload@v1.0.0
      with:
        account_name: templatez
        account_key: ${{secrets.ACCOUNT_KEY}}
        share_name: teste
        source_dir: templates
        cloud: AzureUSGovernment
    
    # - name: Acessar diretório raiz do projeto
    #   run: |
    #     cd ${{ github.workspace }}
    #     ls

    
    # - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
    #   name: Azure Blob Upload with Destination folder defined
    #   with:
    #     connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    #     container_name: templatez
    #     source_folder: src/templates
    #     destination_folder: teste
    #     clean_destination_folder: true