# File: .github/workflows/OIDC_workflow.yml
name: AzureLoginSample
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - name: Acessar diretório raiz do projeto
      run: |
        cd ${{ github.workspace }}
        ls

    
    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Azure Blob Upload with Destination folder defined
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container_name: templatez
        source_folder: src/templates
        destination_folder: teste
        clean_destination_folder: true